# Generated by Django 3.1.5 on 2021-01-31 17:36

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('name', models.CharField(max_length=150, verbose_name='عنوان در URL')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_text', models.TextField()),
                ('pub_date', models.DateField(blank=True, default=datetime.datetime(2021, 1, 31, 21, 6, 39, 999144), null=True)),
                ('pub_time', models.TimeField(blank=True, default=datetime.datetime(2021, 1, 31, 21, 6, 39, 999143), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('pub_date', models.DateField(blank=True, default=datetime.datetime(2021, 1, 31, 21, 6, 40, 140), null=True)),
                ('pub_time', models.TimeField(blank=True, default=datetime.datetime(2021, 1, 31, 21, 6, 40, 140), null=True)),
                ('number_of_comments', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_pingbacks', models.IntegerField(blank=True, default=0, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='eshop_news.Category')),
                ('comments', models.ManyToManyField(to='eshop_news.Comment')),
            ],

        ),
    ]
