# Generated by Django 3.1.5 on 2021-01-31 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_news', '0002_auto_20210131_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pub_time',
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 31, 21, 12, 46, 200485), null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 1, 31, 21, 12, 46, 200484), null=True),
        ),
    ]
