# Generated by Django 3.1.5 on 2021-01-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_news', '0003_auto_20210131_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='pub_time',
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
