# Generated by Django 3.1.5 on 2021-01-31 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_news', '0004_auto_20210131_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.AlterModelTable(
            name='blog',
            table=None,
        ),
    ]
