# Generated by Django 3.1.5 on 2021-02-01 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop_news', '0005_auto_20210131_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
