# Generated by Django 3.1.5 on 2021-02-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_news', '0006_comment_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='user',
        ),
    ]
