# Generated by Django 3.1.5 on 2021-02-02 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop_news', '0007_auto_20210201_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('number_of_comments', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_pingbacks', models.IntegerField(blank=True, default=0, null=True)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(to='eshop_news.Category')),
                ('comments', models.ManyToManyField(to='eshop_news.Comment')),
            ],
        ),
    ]
