# Generated by Django 3.1.5 on 2021-02-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_news', '0008_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='education',
            name='title_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
