# Generated by Django 3.1.5 on 2021-02-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_news', '0009_auto_20210221_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='number_of_comments',
        ),
    ]
