# Generated by Django 3.1.5 on 2021-02-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_news', '0010_remove_education_number_of_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='number_of_comments',
        ),
    ]
