# Generated by Django 3.1.5 on 2021-02-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_news', '0011_remove_blog_number_of_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='eshop_news.Comment'),
        ),
        migrations.AlterField(
            model_name='education',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='eshop_news.Comment'),
        ),
    ]
