# Generated by Django 3.1.5 on 2021-02-22 07:12

from django.db import migrations, models
import eshop_news.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_news', '0012_auto_20210221_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title_image',
            field=models.ImageField(null=True, upload_to=eshop_news.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='education',
            name='title_image',
            field=models.ImageField(null=True, upload_to=eshop_news.models.upload_image_path),
        ),
    ]
