# Generated by Django 3.1.5 on 2021-01-31 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop_products', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eshop_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('bought_products', models.ManyToManyField(to='eshop_products.Product')),
                ('comments', models.ManyToManyField(to='eshop_news.Comment')),
            ],
        ),
    ]
