# Generated by Django 3.2.5 on 2021-09-05 12:07

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eshop_account.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eshop_products_category', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eshop_products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_text', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پاسخ تیکت',
                'verbose_name_plural': 'پاسخ های تیکت',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1500, null=True, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=1500, null=True, verbose_name='شماره موبایل')),
                ('email', models.CharField(blank=True, max_length=1500, null=True, verbose_name='ایمیل')),
                ('body_text', ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'ارتباط',
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1500, null=True)),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='قیمت')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتور ها',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1500, null=True)),
                ('money', models.IntegerField(blank=True, default=0, verbose_name='قیمت')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول ها',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('body_text', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('answers', models.ManyToManyField(blank=True, null=True, to='eshop_account.Answer')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1500, null=True)),
                ('visit', models.IntegerField(blank=True, default=0, verbose_name='بازدید')),
                ('body_text', ckeditor.fields.RichTextField(blank=True, default=None, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('answers', models.ManyToManyField(blank=True, null=True, to='eshop_account.Answer')),
                ('category', models.ManyToManyField(blank=True, null=True, to='eshop_products_category.ProductCategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('bio', models.CharField(blank=True, max_length=1500, null=True)),
                ('skills', models.CharField(blank=True, max_length=1500, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=eshop_account.models.upload_image_path)),
                ('prof', models.BooleanField(default=False, verbose_name='استاد')),
                ('vip', models.BooleanField(default=False, verbose_name='کاربر خاص')),
                ('advisor', models.BooleanField(default=False, verbose_name='مشاور')),
                ('bought_products', models.ManyToManyField(blank=True, null=True, to='eshop_products.Product')),
                ('factors', models.ManyToManyField(blank=True, null=True, to='eshop_account.Factor')),
                ('questions', models.ManyToManyField(blank=True, null=True, to='eshop_account.Question')),
                ('tickets', models.ManyToManyField(blank=True, null=True, to='eshop_account.Ticket')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop_account.wallet')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
    ]
