# Generated by Django 3.1.5 on 2021-02-22 07:12

from django.db import migrations, models
import eshop_account.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0002_remove_profile_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=eshop_account.models.upload_image_path),
        ),
    ]
