# Generated by Django 3.1.5 on 2021-02-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_news', '0008_education'),
        ('eshop_products', '0002_auto_20210201_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.ManyToManyField(to='eshop_news.Comment'),
        ),
    ]
