# Generated by Django 3.1.5 on 2021-02-21 07:16

from django.db import migrations, models
import eshop_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0003_product_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='teacher',
            field=models.CharField(default=None, max_length=150, verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to=eshop_products.models.upload_image_path),
        ),
    ]
