# Generated by Django 3.1.5 on 2021-02-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0004_auto_20210221_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skill',
            field=models.CharField(default=None, max_length=150, verbose_name='مهارت'),
        ),
    ]
