# Generated by Django 3.1.5 on 2021-02-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0005_product_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='skill',
            field=models.CharField(default=None, max_length=150, null=True, verbose_name='مهارت'),
        ),
    ]
