# Generated by Django 3.1.5 on 2021-02-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_news', '0012_auto_20210221_2211'),
        ('eshop_products', '0008_auto_20210221_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='eshop_news.Comment'),
        ),
        migrations.AlterField(
            model_name='product',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, to='eshop_products.Videos'),
        ),
    ]
